### ISSUE TITLE
I don't see a difference in energy for tautomers

### ISSUE THREAD

**Issue by PatWalters** [isayevlab/Auto3D_pkg#22]
I don't see a difference in energy for tautomers.  I use this SMILES for sildenafil as input 
CCCC1=NN(C2=C1N=C(NC2=O)C3=C(C=CC(=C3)S(=O)(=O)N4CCN(CC4)C)OCC)C sildenafil

auto3D.py correctly generated 3 tautomers
CCCc1c2c(c(=O)[nH]c(n2)c3cc(ccc3OCC)S(=O)(=O)N4CCN(CC4)C)n(n1)C sildenafil@taut1
CCCc1c2c(c(=O)nc([nH]2)c3cc(ccc3OCC)S(=O)(=O)N4CCN(CC4)C)n(n1)C sildenafil@taut2
CCCc1c2c(c(nc(n2)c3cc(ccc3OCC)S(=O)(=O)N4CCN(CC4)C)O)n(n1)C sildenafil@taut3

However, the tautomers have the same energy and "E_rel(kcal/mol)" is 0 for all three tautomers.  I don't think this is correct.  If we look at the literature sildenafil@taut1 and sildenafil@taut2 are predominant.  
https://link.springer.com/article/10.1007/s11224-021-01818-7

I've run several other examples and the tautomers are always equinenergetic.   Am I missing something?  The commandline I used was
python ~/software/Auto3D_pkg/auto3D.py sildenafil.smi --k=1 --enumerate_tautomer=True

**Comment by isayev** [comment]
Pat:
Thanks for reporting! This is clearly a bug. We have been implementing some
new functionality and probably broken the code! I wish we made a stable 1.0
release.

**Comment by LiuCMU** [comment]
Hi Pat, thanks for the feedback!

I guess you got the correct output, but misunderstood `<E_tot>` and `<E_rel(kcal/mol)>`. 

`E_tot`  is the energy for each molecule (unit Hartree). The values are different for all structures. You will see that @taut25, @taut26 and @taut27 have the lowest energies (in the attached file), which is consistent with that paper. 

`E_rel(kcal/mol)` reflects the relative energies of different 3D conformers of the same molecule. In your case --k=1, so only the lowest-energy conformer for each tautomer was in the output. If you set k to a larger number, say --k=3. Then for each tautomer, there will be 3 conformers (so there will be 28*3 structures in the final output). There will be a relative energy difference between the 3 conformers for each tautomer.

So you got a list of 3D tautomers with energies, it’s one more step to select the tautomers with the lowest energies. 


One caveat is that RDKit generates all possible tautomers regardless of its stability. Using the sildenafil SMILES as the input, I run the auto3d using the same command line tool. Here is my output (please change the file extension back to sdf for visualization): 
[test_out.txt](https://github.com/isayevlab/Auto3D_pkg/files/9668184/test_out.txt)

In my case, the final output contains 28 structures, each of which is the lowest energy for its corresponding tautomer type. Based on your input parameters, auto3d runs with RDKit as the tautomer generator. Did you only get 3 tautomers or you selected the 3 tautomer examples in the previous message?

**Comment by LiuCMU** [comment]
BTW, could you share your output file,so that I can take a look? Please feel free to let us know if you have any questions or improvement suggestions.

**Comment by PatWalters** [comment]
I ran sildenafil with this input 
CCCC1=NN(C2=C1N=C(NC2=O)C3=C(C=CC(=C3)S(=O)(=O)N4CCN(CC4)C)OCC)C sildenafil
I then used this commandline
python ~/software/Auto3D_pkg/auto3D.py sildenafil.smi --k=1 --enumerate_tautomer=True

This generated 3 tautomers.  Note that I have OEChem installed so I'm using the OpenEye Tautomer engine.  I got 3 tautomers in my output.   I've attached the SDF.  

The relative energies of the tautomers doesn't look right.  According to the paper mentioned above, the two keto forms are lower in energy, while the enol form is higher in energy. 

SMILES,ID,delta_E
CCCc1nn(C)c2c(=O)[nH]c(-c3cc(S(=O)(=O)N4CCN(C)CC4)ccc3OCC)nc12,sildenafil@taut1,0.0
CCCc1nn(C)c2c(=O)nc(-c3cc(S(=O)(=O)N4CCN(C)CC4)ccc3OCC)[nH]c12,sildenafil@taut2,20.08775884541683
CCCc1nn(C)c2c(O)nc(-c3cc(S(=O)(=O)N4CCN(C)CC4)ccc3OCC)nc12,sildenafil@taut3,13.294504359131679
[sildenafil_out.sdf.txt](https://github.com/isayevlab/Auto3D_pkg/files/9670137/sildenafil_out.sdf.txt)

delte_E is the difference in energy, in kcal/mol from the lowest. 

taut1 and taut2 are the keto forms and taut3 is the enol form. Notice that energy for taut3 is between the energy for taut 1 and taut3, which is not correct. 

Would I get better results by generating more conformers and Boltzmann weighting the results?

**Comment by LiuCMU** [comment]
I see, there is a discrepancy between the relative energies of tautomer2 and tautomer3, when comparing the auto3d results and the paper.

The simplest way is to try another optimization engine. For now, you used AIMENT; you can try ANI2x by adding `--optimizing_engine=ANI2x`. The optimization engines are included for different application purposes. Unfortunately, the ANI-2xt model is not publically available yet, we will try to give it public soon.

The other thing that you can do is to use a higher DFT method to do single-point energy calculations, using the 3D structures as the input. The original paper used B3LYP, which is not a very accurate DFT method. AIMNET was trained to mimic B97-3c. ANI-2x was trained to mimic w97X/6-31G*. So it's good to have the SPE from these two DFT methods. The enol form contains 3 aromatic rings, which may also provide some stability.

**Comment by PatWalters** [comment]
Apologies, I shouldn't have referred to the results in the paper as "correct" :-).   I'm going to mess around with this a bit more to understand what's happening.   Thanks for making such a useful resource available! 
For what it's worth, the Schrödinger tautomer workflow M06-2X / cc-pVTZ(-f) says a zwitterionic species is predominant. 
CCCc1nn(C)c2c([O-])nc(-c3cc(S(=O)(=O)N4CC[NH+](C)CC4)ccc3OCC)nc12.  Experimental data shows the pKa of the piperazine is 6.78.  The bottom line is that this is tricky business.

**Comment by LiuCMU** [comment]
No worries, you are good. You are helping us to make auto3d better by providing feedback and discussing with us. I appreciate that 👍   This is actually good benchmark for an important drug.

I had some difficulty in reproducing your results. I ran auto3d with:
```
python /home/jack/Auto3D_pkg/auto3D.py test.smi --k=1 --enumerate_tautomer=True  --verbose=True
```
The `--verbose=True` does not change the package behavior, but records some meta data during the running process for degugging. 

The `test.smi` contains:
```
CCCC1=NN(C2=C1N=C(NC2=O)C3=C(C=CC(=C3)S(=O)(=O)N4CCN(CC4)C)OCC)C sildenafil
```
The above experiment should generate tautomers using the default setting (i.e. RDKit), build initial 3D conformers with the default setting (i.e. RDKit), optimize with the default engine (i.e. AIMNET). 

So I'm suprised if OpenEye tautomer engien was used to generate tautomers, because the following commands would ask auto3d to use the default tautomer generation engine (rdkit), default the 3d building engine (rdkit) and default optimizing engine(AIMNET). Could you maybe run your experiment again with `--verbose=True`, so that I can take a look at the job folder with meta data? There could be a bug if auto3d used openeye tautomer engine in this experiment. 
> I ran sildenafil with this input
> CCCC1=NN(C2=C1N=C(NC2=O)C3=C(C=CC(=C3)S(=O)(=O)N4CCN(CC4)C)OCC)C sildenafil
> I then used this commandline
> python ~/software/Auto3D_pkg/auto3D.py sildenafil.smi --k=1 --enumerate_tautomer=True
> This generated 3 tautomers. Note that I have OEChem installed so I'm using the OpenEye Tautomer engine. I got 3 tautomers in my output. I've attached the SDF.

I'm also testing auto3d with ani-2x and ani-2xt in my end with the sildenafil moleucle, using `--tautomer-engine=oechem  --isomer_engine=omega`. But openeye/oechem software only gave me 1 tautomer, which is the second problem I met. Would mind tell me your openeye-toolkit version? Thanks!

**Comment by PatWalters** [comment]
I ran with the same command
python /home/jack/Auto3D_pkg/auto3D.py test.smi --k=1 --enumerate_tautomer=True  --verbose=True

I ended up with 3 tautomers. Here's my logfile and the verbose.tar.gz from the job1 directory

[Auto3D.log](https://github.com/isayevlab/Auto3D_pkg/files/9677922/Auto3D.log)
[verbose.tar.gz](https://github.com/isayevlab/Auto3D_pkg/files/9677925/verbose.tar.gz)

**Comment by PatWalters** [comment]
According to logfile I'm using the RDKit as the tautomer and conformed engines.

**Comment by LiuCMU** [comment]
Hey, thanks for the information! Yes, the log file showed that the tautomers and conformers were generated via RDKit. This is confirmed by the existence of the `smiles_enumerated_hashed.smi` file in the `verbose.tar.gz`. This file only exists when RDKit was used as the isomer engine (i.e. generates the initial 3D structures). Good news for me -- no bug in the auto3d control interface.

Now the interesting issue is that we got different number of tautomers, though both of us used RDKit to generate tautomers. This is probably because RDKit changed their tautomer enumeration function in a newer update:
>The rules for tautomer enumeration in MolStandardize have been updated to
more closely match the rules in the original publication. These changes
primarily consist of making the rules more specific; the consequence is that
less tautomers will be generated with this version. The previous rules can
still be accessed via the function GetV1TautomerEnumerator() (Python) or
getV1TautomerEnumerator() (C++)
[link to the release notes](https://github.com/rdkit/rdkit/releases?q=GetV1TautomerEnumerator&expanded=true#:~:text=The%20rules%20for%20tautomer,getV1TautomerEnumerator()%20(C%2B%2B)) 

In light of this, let's keep using RDKit as the `tauto_engine` for now. I will try ANI-2xt and ANI-2x to check the relative energies of the 3 tautomers in the above. Yeah, finally marching into the energy issue...

**Comment by LiuCMU** [comment]
If you are curious about the tautomer generator from OpenEye, they have a issue: Sometimes the generator includes the input molecule as part of the output, but sometimes not. Specifically, the input itself is returned when it does not have tautomers; the input is not included when it has some tautomers. So oequacpac.OEGetReasonableTautomers has incosistent output. Below is an example that I showd to their support team:

> Example 1: only the enol form was returned (CC(O)=CC(C)=O) when the input was the keto form (CC(CC(C)=O)=O). 
> Example 2: butane (CCCC) was returned when the input was butane (CCCC).
> 
> Scripts for reproduction:
>         from openeye import oechem
>         from openeye import oequacpac
>         from openeye import oeomega
>         input, output = path1, path2
>         ifs = oechem.oemolistream()
>         ifs.open(input)
> 
>         ofs = oechem.oemolostream()
>         ofs.open(output)
> 
>         tautomerOptions = oequacpac.OETautomerOptions()
>         pKaNorm = True
> 
>         for mol in ifs.GetOEGraphMols():
>             for tautomer in oequacpac.OEGetReasonableTautomers(mol, tautomerOptions, pKaNorm):
>                 oechem.OEWriteMolecule(ofs, tautomer)
> 
> In example 1, both the keto and enol forms are common tautomeric forms. Only the enol form was returned, which seems to suggest that OEGetReasonableTautomers does not include the input molecule as part of the function output. However, for example2, the input was included as part of the function output. 
> 
> 
> Openeye software:  openeye-toolkits via Anaconda (version 2021.2.0; Build py37_0; Channel openeye)
> System: Ubuntu 20.04.1
> 
They probably haven't fix it now. So I included the input SMILES as part of the output when using OpenEye to generate tautomers when implementing auto3d. By doing so, I avoided the risk of missing a tautomer, but the drawback is that there will be a duplicate tautomer when OpenEye happens to include the SMILES in the input.

**Comment by LiuCMU** [comment]
I was able to reproduce your results after updating RDKit to 2022.03.1 (which I will set as the requriement for auto3d in the future). Here is a summary:

|Job_name|Tautomer Engine|Optimizing Engine | E(taut1, Hartree)|E(taut2 - taut1, kcal/mol)|E(taut3 - taut1, kcal/mol)|
|-|-|-|-|-|-|
|rdkit-aimnet|RDKit|AIMNET|-1885.2230|20.1|12.9|
|rdkit-ani2x|RDKit|ANI-2x|-1883.5950|15.2|15.1|
|rdkit-ani2xt|RDKit|ANI-2xt|-1883.2396|14.5|23.3|

taut1: CCCc1c2c(c(=O)[nH]c(n2)c3cc(ccc3OCC)S(=O)(=O)N4CCN(CC4)C)n(n1)C
taut2: CCCc1c2c(c(=O)nc([nH]2)c3cc(ccc3OCC)S(=O)(=O)N4CCN(CC4)C)n(n1)C 
taut3: CCCc1c2c(c(nc(n2)c3cc(ccc3OCC)S(=O)(=O)N4CCN(CC4)C)O)n(n1)C
For all jobs, 3D conformers were initially generated by RDKit.
I included my output folders here: [Archive.zip](https://github.com/isayevlab/Auto3D_pkg/files/9678564/Archive.zip)

The above experiments were run with the following commands:
```
python /home/jack/Auto3D_pkg/auto3D.py test.smi --k=1 --enumerate_tautomer=True --verbose=True --optimizing_engine=AIMNET --job_name=rdkit-aimnet

python /home/jack/Auto3D_pkg/auto3D.py test.smi --k=1 --enumerate_tautomer=True --verbose=True --optimizing_engine=ANI2x --job_name=rdkit-ani2x

python /home/jack/Auto3D_pkg/auto3D.py test.smi --k=1 --enumerate_tautomer=True --verbose=True --optimizing_engine=ANI2xt --job_name=rdkit-ani2xt
```

So the away is that:

- ANI-2xt gives the closest result to that paper, in terms of the relative energies of the 3 tautomers;
- Using RDKit >= 2022.03.1 for tautomer generation is the optimal choice (older versions enumerate all possible tautomers regardless of stability)
- we need to make ANI-2xt public by incorporating it into the current TorchANI package.

I hope these results cleared some confusions.

**Comment by PatWalters** [comment]
This is great, I owe you a beer!

**Comment by LiuCMU** [comment]
Thanks for supporting us! I will buzz you once ANI-2xt is publicly available. 

The auto3d project was designed to get the low-energy 3D conformers for general molecules (i.e. no emphasis on tautomers), so we thought it was not urgent to include ANI-2xt (where t stands for tautomer) in the package. As the paper is out, we received much interest in the tautomers. So it's on agenda to incorporate the ANI-2xt into TorchANI. For tasks that don't heavily involve tautomers, the ANI-2x and AIMNET work pretty well, too.

**Comment by aniketsh** [comment]
@LiuCMU Thank you for integrating this. Would it be possible to add % boltzmann population for each top tautomer?

**Comment by LiuCMU** [comment]
Hey @PatWalters ,

We finally incorporated ANI-2xt in Auto3D! ANI-2xt is now public and can be used by everyone. To use it, you can upgrade auto3d by `pip install auto3d --upgrade` (should be version 2.0), then use the argument `optimizing_engine="ANI2xt"`. 

Please note that this public ANI-2xt is slightly different than the one we used in the original paper. I used it to do the same experiment on the sildenafil example. Here is the energy ranking (the 4th row, the trend is the same as expected):

|Job_name|Tautomer Engine|Optimizing Engine | E(taut1, Hartree)|E(taut2 - taut1, kcal/mol)|E(taut3 - taut1, kcal/mol)|
|-|-|-|-|-|-|
|rdkit-aimnet|RDKit|AIMNET|-1885.2230|20.1|12.9|
|rdkit-ani2x|RDKit|ANI-2x|-1883.5950|15.2|15.1|
|rdkit-ani2xt|RDKit|ANI-2xt|-1883.2396|14.5|23.3|
|rdkit-ani2xt public|RDKit|ANI-2xt public|-1883.2380|12.6|16.5|

taut1: CCCc1c2c(c(=O)[nH]c(n2)c3cc(ccc3OCC)S(=O)(=O)N4CCN(CC4)C)n(n1)C
taut2: CCCc1c2c(c(=O)nc([nH]2)c3cc(ccc3OCC)S(=O)(=O)N4CCN(CC4)C)n(n1)C 
taut3: CCCc1c2c(c(nc(n2)c3cc(ccc3OCC)S(=O)(=O)N4CCN(CC4)C)O)n(n1)C
For all jobs, 3D conformers were initially generated by RDKit.

**Comment by LiuCMU** [comment]
Besides, a new function was implemented: `get_stable_tautomers`. It can select stable tautomers (`tauto_k`) for the input SMILES. The tautomers are ranked based on the energies of their conformers. To use this function, you can either import it as a module from auto3D or use the [`tauto_interface.py`](https://github.com/isayevlab/Auto3D_pkg/blob/f463e4fd072d3e219b709cfb2b127146db05339c/tauto_interface.py) to run from the command line.
```
# import as a python module
import Auto3D
from Auto3D.auto3D import options, main
from Auto3D.tautomer import get_stable_tautomers


if __name__ == "__main__":
    print(Auto3D.__version__)
    input_path = "test.smi"
    args = options(input_path, k=1, enumerate_tautomer=True,
                              optimizing_engine="ANI2xt", gpu_idx=0)
    out = get_stable_tautomers(args, tauto_k=3)

#OR run from command line
python tauto_interface.py "test.smi" --k=1 --enumerate_tautomer=True --optimizing_engine="ANI2xt" --tauto_k=3
```
Please note: To boost efficiency, the `get_stable_tautomer` function by default uses a small `patience` number and a small `max_confs` for each tautomer. Specifically, we only enumerate 10 conformers for each tautomer (not as exhaustive as for conformed search) then optimize and rank the tautomers based on their conformed energies. The idea is that if a tautomer is more stable, then it is more likely to give stable conformers than other tautomers. Since this function uses a small number of conformers, so the values of relative energies could change from run to run, but the order should stay the same.

The output of this function is also an `SDF` file ending with `_top_tautomers.sdf"`, where the `E_tautomer_relative(kcal/mol)` gives the relative energies of all tautomers for an input SMILES.

To avoid confusion, the following 2 figures demonstrate the ranking process for conformer search and tautomer search, respectively.

![confomer_tautomer_search](https://user-images.githubusercontent.com/60156077/215158840-5823ded7-4fc8-464e-80f4-f8ee4965eefb.png)

Top image: For the conformer searching process, only conformers of the same tautomers are ranked (highlighted in blue). The SDF file records the relative energies of different conformers;

Bottom image: For the tautomer searching process, conformers for all tautomers are grouped and ranked according to their energies (highlighted in orange). The SDF file records the relative energies of conformers from all tautomers. 

There is still a lot to be done about the documentation, sorry for the confusion. Please let me know if you have any additional questions.
