### ISSUE TITLE
 Import StandaloneRepulsionCalculator Error

### ISSUE THREAD

**Issue by xiaolinpan** [isayevlab/Auto3D_pkg#24]
Hi, 

Thanks for your excellent work and sharing the source code!

When the script imports "StandaloneRepulsionCalculator" function from torchani,  the error occurred.

I don't find the function in torchani repo, could you tell me which version of torchani should be installed?

Many thanks for your help!

`
Traceback (most recent call last):
  File "get_ani_2xt.py", line 12, in <module>
    from Auto3D.batch_opt.ANI2xt import ANI2xt
  File "/home/xlpan/solv_env_rdkit/lib/python3.6/site-packages/Auto3D/batch_opt/ANI2xt.py", line 6, in <module>
    from torchani.repulsion import StandaloneRepulsionCalculator
`

**Comment by LiuCMU** [comment]
Hey, thanks for supporting Auto3D!

This is expected behavior. `StandaloneRepulsionCalculator` is in the development stage of the TorchANI project, so it's only visible to developers. The consequence is that `ANI-2xt` is not available in Auto3D. For now, you can use`ANI-2x` or `AIMNET`as the optimizing engine, they give decent results for most tasks.

We are sorry for the inconvenience. I will try to release a public ANI-2xt that doesn't rely on `StandaloneRepulsionCalculator` soon.

**Comment by xiaolinpan** [comment]
Thanks for your reply!

I will try to use ANI-2x and AIMNET.

Looking forward to the release of the ANI-2xt.
