### ISSUE TITLE
TorchANI with repulsion calculator is not installed.

### ISSUE THREAD

**Issue by mrinal-shekhar** [isayevlab/Auto3D_pkg#25]
Hi 
I was trying to replicate tautomer generation using the following command
python auto3D.py test.smi --k=1 --enumerate_tautomer=True --verbose=True --optimizing_engine=ANI2xt --job_name=rdkit-ani3
I end up getting the following error
ANI2xt is used as optimizing engine, but TorchANI with repulsion calculator is not installed.

The following command works fine for me
python auto3D.py test.smi --k=1 --enumerate_tautomer=True --verbose=True --optimizing_engine=AIMNET --job_name=rdkit-aimnet

Mrinal

**Comment by LiuCMU** [comment]
Hey, thanks for supporting Auto3D!

This is expected behavior. TorchANI with repulsion calculator is in the development stage of the TorchANI project, so it's only visible to developers. The consequence is that `ANI-2xt` is not available in Auto3D. For now, you can use `ANI-2x` or `AIMNET` as the optimizing engine, they give decent results for most tasks.

We are sorry for the inconvenience. I will try to release a public ANI-2xt that doesn't rely on the repulsion calculator soon.

**Comment by aniketsh** [comment]
Any update on the release of ANI-2xt?

**Comment by LiuCMU** [comment]
Hey @mrinal-shekhar and @aniketsh 

ANI2xt was finally incorporated into Auto3D 2.0, yeah! You can use `ANI2xt` by updating auto3d to the newest version
```
pip install auto3d --upgrade
```
This `ANI2xt` avoided the repulsion calculator and is mostly similar to the one with the repulsion calculator. We are also developing some new features about tautomers and improving the documents as auto3d is getting larger and larger. Please let me know if you have any questions about using `Auto3D`.
