### ISSUE TITLE
ionization states

### ISSUE THREAD

**Issue by zhengmin317** [isayevlab/Auto3D_pkg#28]
Is it possible to include the ionization states in the output file of the 3D small molecules?

**Comment by LiuCMU** [comment]
Hey, thanks for the question!

SDF file records the charges on each atom by design. In the Atom Block, the first 3 numbers are the XYZ coordinate, then comes the atomic symbol, and the following number represents the charge state on the atom. For more details, see [here](https://www.nonlinear.com/progenesis/sdf-studio/v0.9/faq/sdf-file-format-guidance.aspx#:~:text=The%20Atoms%20block,or%20Progenesis%20MetaScope.)  

If you want partial atomic charges, they can be calculated using the [AIMNET-NSE](https://github.com/isayevlab/aimnetnse) model. It accepts the SDF as input.

Please let me know if you have additional questions.

**Comment by zhengmin317** [comment]
Thanks for the prompt reply!
The ionization states I was talking about are protonation and deprotonation states.
When the input is "CNCCC1=CC=CC=C1 smi1", the output is as the following figure.  A neutral molecule is given.
However, a positively charged molecule with a protonated Nitrogen atom is expected to be a favorable conformation in an aqueous solution.
![image](https://user-images.githubusercontent.com/16145132/210923101-979b4165-428a-4006-9e1a-b4af743d12b3.png)

**Comment by LiuCMU** [comment]
I see, you were trying to find the proper protonation states of a molecule under the aqueous environment. 

That's a different function from Auto3D's design. Auto3D was designed to generate the low-energy 3D conformers for the given SMILES. It tries to enumerate and optimize all possible conformers than output the most stable conformers. All these conformers are consistent with the input SMILES. Auto3D does not change the molecules, but just build conformers.

BTW, our models only work in vacuum so far.

**Comment by isayev** [comment]
@zhengmin317 our future models very soon will include the solvent effect in the continuum approximation (e.g. PCM or SMD), so you would be able to explore different protonation states. However, as of today, all calculations are gas phase only.
