### ISSUE TITLE
Maximum SMILES length?

### ISSUE THREAD

**Issue by rish-16** [isayevlab/Auto3D_pkg#34]
Hey, thanks for the library! I was hoping to find out if there’s a maximum SMILES string length that’s accepted by the model. Or any observed length after which the quality of predictions degrades. 

Thank you!

**Comment by LiuCMU** [comment]
Hi, thanks for supporting Auto3D!

There is no maximum SMILES length requirement in Auto3D. There are some general aspects to think about when considering Auto3D for your SMILES:

- Can the SMILES be processed by RDKit? Auto3D utilizes RDKit for many tasks, such as isomer enumeration, initial 3D structure building, etc. Some SMILES might be too large, and RDKit cannot process them correctly.
- Can NNPs give reliable predictions? The NNPs in Auto3D are trained with molecules with up to 16 heavy atoms. They are well suited for small-to-medium-size molecules. These NNPs showed very good performance on many larger molecules (i.e. 100 heavy atoms), because these NNPs internally represent molecules using atomic vectors, which are independent of molecule size. However, the long-range interactions within a molecule may be ignored.

The short answer is that you could try Auto3D on any SMILES. In cases where you think the prediction is not reasonable, feel free to verify 1 or 2 examples with the B97-3c method.

**Comment by rish-16** [comment]
Awesome, thanks for the info!
